### PR TITLE
Support 0.14.0-beta1 usage

### PR DESCRIPTION
**Pull request by slorber**
see https://github.com/gaearon/react-hot-api/issues/18

### CODE REVIEW

**Comment by gaearon** [comment]
Hi! Have you verified whether it works with this version?

**Comment by slorber** [comment]
no :( just submited the PR so that you won't forget to add the beta to the list (if it works)

**Comment by chicoxyzzy** [comment]
@slorber didn't noticed your PR and made my own #21. I'll close it now. I've verified. @gaearon RHL works fine but you should also publish new version of RHL with these changes https://github.com/gaearon/react-hot-loader/commit/bac56777c7885314e94ee4934129435cfda02c27 first

**Comment by chicoxyzzy** [comment]
yay!

**Pull request merged**
