### PR TITLE
Allow any version of react 0.14-beta as peerDependencies

### LINKED ISSUE #18: add new beta 0.14 to peerDependencies
As far as I understand, NPM messes up when trying to depend both `0.14.0-beta1` and on libraries that has declared React as a peerDependency. 

For example 

```
    "react": "0.14.0-beta1",
    "react-date-picker": "2.0.15",
```

Does not work well because `react-date-picker` has `peerDependency >= 0.13.0`

I've seen this commit which seems to be your solution to this problem (that I could validate on my computer for react-date-picker), so I simply add 0.14.0-beta1 to the list.
https://github.com/gaearon/react-hot-api/commit/c11de6c89cf2e5908436580d1689c39adb1c7b2b

By the way, isn't there any better solution? Should I contact every lib author to make the change so that I'm able to use that beta? :'(

### PR DESCRIPTION
**Pull request by themouette**
Fixes #18

### CODE REVIEW

**Comment by cesarandreu** [comment]
+1

@gaearon Would you consider just publishing this under a beta tag or something along those lines?

**Comment by gaearon** [comment]
Out in 0.4.6.
Sorry for big delay.
I'm working on revamping this whole thing as [react-proxy](https://github.com/gaearon/react-proxy) so stay tuned. :-)

**Comment by cesarandreu** [comment]
Awesome, thanks!

**Comment by themouette** [comment]
thank you

**Pull request merged**
