### PR TITLE
Fix issue #15 makeAssimilatePrototype invokes getters when copying me…

### PR DESCRIPTION
**Pull request by timnew**
Well, it seems this approach solved the issue

### CODE REVIEW

**Comment by timnew** [comment]
This pull request is intended to fix https://github.com/gaearon/react-hot-loader/issues/131

**Comment by gaearon** [comment]
Thanks! I have a busy week but I'll come around to check this out in a week or so.

**Comment by jhollingworth** [comment]
:+1: I've just been having troubles with this

**Comment by jquense** [comment]
not trying to be that guy, but any chance we will see this merged and released? I need to turn off hot loading otherwise

**Comment by benmosher** [comment]
Just replaced npm's tip version of `react-hot-api` with this and my local `react-hot-loader` is working with my custom `@bind`-decorated methods (replaces method with a getter that binds on the way out, like a forced `::this.whatever`).

AFAIK, this is more generally correct in the spirit of what the patching is attempting to do. :+1:

**Comment by gaearon** [comment]
>not trying to be that guy, but any chance we will see this merged and released? I need to turn off hot loading otherwise

I don't have time right now. I'm focused on getting Redux 1.0 out. I don't want to release a fix I have not tested extensively because it might break other people's stuff, and then I'd have to spend even more time when I don't have any.

I will get back to improving React Hot Loader later this month, and then I'll make sure to merge this and other important fixes. Please have some more patience. :-)

**Comment by benmosher** [comment]
FYI, folks can use this in the interim by:
- removing `react-hot-loader` (`npm r react-hot-loader --save-dev`)
- install `timnew/react-hot-api` (`npm i timnew/react-hot-api --save-dev`)
- _then_ install `react-hot-loader` 1.2.7 (`npm i react-hot-loader@1.2.7 --save-dev`)

`1.2.8` is not compatible with `react-hot-api` 1.4.4 and would thus install its own version in its node_modules.

This is working for me, but I'm pretty new to React hot loading so I'm not sure what could go wrong. :sweat_smile:

**Comment by gaearon** [comment]
Thanks for providing interim instrutions @benmosher!

**Comment by gaearon** [comment]
This is fixed in [React Proxy](https://github.com/gaearon/react-patch) in a slightly more accurate way.
I'll soon migrate RHA to use it, stay tuned.

Thanks for the PR!

**Pull request closed without merging**
